### ISSUE TITLE
Testnet 003 checklist

### ISSUE THREAD

**Issue by webmaster128** [noislabs/testnets#3]
What do we want to change for testnet-003? Collecting ideas here:

- [x] Small blocks (3 million gas)
- [x] Shorter block times (3 seconds?)
- [x] Reduce active validators 100 -> 40
- [x] Use wasmd 0.29
- [x] Bring back slashing params to default
- [x] Reduce supply 2M -> 100M supply
- [x] 500K tokens to be staked by validator (staked/total supply 20%)
- [x] Unbonding period: 21 -> 1 day

**Comment by webmaster128** [comment]
> Decrease the unbonding period ?

Sure, 1 day?

**Comment by webmaster128** [comment]
I'd keep the supply at 100 million NOIS. Otherwise we also need to cut the gas price by 100, making it hard to re-configure everything from 0.05unois to 0.0005unois.

**Comment by webmaster128** [comment]
> yeah, or because we're planning better this time maybe we can keep the default value of 21 then we don't need to unbond ?

Flexibility is more important than security for the testnet. Let's do 1 day.

**Comment by webmaster128** [comment]
I think we need to increase the block gas limit a bit. Currently uploading the oracle takes 3069628 gas. The CLI sets the gas limit to 3666386 when using `--gas auto --gas-adjustment 1.2`. Can we use 4 million instead of 3 million for testnet 3 to avoid unnecessary trouble?

**Comment by webmaster128** [comment]
done
